title: 3lvis.net blog
email: elvisnunez@me.com
description: >
  This is a blog about technology, cooking, design, photography and more.
baseurl: ""
url: "http://3lvis.net"
twitter_username: 3lvis
github_username:  3lvis
avatar: http://s.gravatar.com/avatar/50a95dbddde877a2bd7bb5eb103adaea?s=80
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
